# Generated by Django 3.1 on 2020-08-13 19:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usermgmt', '0003_auto_20200813_1821'),
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='unique_code',
        ),
        migrations.AddField(
            model_name='transaction',
            name='apikey',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='usermgmt.apiaccesskey'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='checkour_code',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
