# Generated by Django 3.1 on 2020-08-13 19:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0002_auto_20200813_1929'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='checkour_code',
            new_name='checkout_code',
        ),
    ]
