# Generated by Django 3.1 on 2020-08-13 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0004_auto_20200813_2104'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='transaction_res',
            field=models.CharField(default='', max_length=1000),
        ),
    ]
