# Generated by Django 3.1 on 2020-08-13 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usermgmt', '0002_apiaccesskey'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apiaccesskey',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
